export const Tax = [
  { value: "ssn", label: "Social Security Number (SSN/TIN)" },
  { value: "ein", label: "EIN" },
];

export const TaxTypes = [
  { value: "sole-proprietorship", label: "Sole proprietorship" },
  { value: "partnership", label: "Partnership" },
  { value: "llc", label: "Limited liability company (LLC)" },
  { value: "corporation", label: "Corporation" },
];

export const InsuranceProviders = [
  { value: "hiscox", label: "Hiscox" },
  { value: "the-hartford", label: "The Hartford" },
  { value: "next-insurance", label: "Next Insurance" },
  { value: "simply-business", label: "Simply Business" },
  { value: "progressive-commercial", label: "Progressive Commercial" },
  { value: "state-farm", label: "State Farm" },
  { value: "travelers", label: "Travelers" },
  { value: "nationwide", label: "Nationwide" },
  { value: "farmers-insurance", label: "Farmers Insurance" },
  { value: "liberty-mutual", label: "Liberty Mutual" },
  { value: "chubb", label: "Chubb" },
  { value: "cna-insurance", label: "CNA Insurance" },
  { value: "allstate", label: "Allstate" },
  { value: "aig", label: "AIG" },
  { value: "berkshire-hathaway-guard", label: "Berkshire Hathaway GUARD" },
  { value: "zurich-insurance-group", label: "Zurich Insurance Group" },
  { value: "amtrust-financial", label: "AmTrust Financial" },
  { value: "markel", label: "Markel" },
  {
    value: "philadelphia-insurance-companies",
    label: "Philadelphia Insurance Companies",
  },
  {
    value: "allianz-global-corporate-specialty",
    label: "Allianz Global Corporate & Specialty",
  },
  { value: "coverwallet", label: "CoverWallet" },
  { value: "thimble", label: "Thimble" },
  { value: "biberk", label: "BiBERK" },
  { value: "assuredpartners", label: "AssuredPartners" },
  { value: "tokio-marine-hcc", label: "Tokio Marine HCC" },
  { value: "axa", label: "AXA" },
  { value: "american-family-insurance", label: "American Family Insurance" },
  { value: "qbe-insurance", label: "QBE Insurance" },
  { value: "usaa", label: "USAA" },
  { value: "pure-insurance", label: "PURE Insurance" },
  { value: "hanover-insurance-group", label: "Hanover Insurance Group" },
  { value: "safety-national", label: "Safety National" },
  { value: "emc-insurance-companies", label: "EMC Insurance Companies" },
  { value: "westfield-insurance", label: "Westfield Insurance" },
  {
    value: "old-republic-insurance-company",
    label: "Old Republic Insurance Company",
  },
  { value: "sentry-insurance", label: "Sentry Insurance" },
  { value: "acuity-insurance", label: "Acuity Insurance" },
  { value: "erie-insurance", label: "Erie Insurance" },
  {
    value: "great-american-insurance-group",
    label: "Great American Insurance Group",
  },
  { value: "auto-owners-insurance", label: "Auto-Owners Insurance" },
  { value: "mutual-of-omaha", label: "Mutual of Omaha" },
  {
    value: "first-insurance-company-of-america",
    label: "First Insurance Company of America",
  },
  { value: "selective-insurance", label: "Selective Insurance" },
  { value: "arch-insurance-group", label: "Arch Insurance Group" },
  { value: "ironshore", label: "Ironshore" },
  { value: "hudson-insurance-group", label: "Hudson Insurance Group" },
  { value: "aspen-insurance", label: "Aspen Insurance" },
  { value: "compwest-insurance-company", label: "CompWest Insurance Company" },
  { value: "rli-corp", label: "RLI Corp." },
  { value: "penn-national-insurance", label: "Penn National Insurance" },
  {
    value: "church-mutual-insurance-company",
    label: "Church Mutual Insurance Company",
  },
  { value: "grange-insurance", label: "Grange Insurance" },
  { value: "united-fire-group-ufg", label: "United Fire Group (UFG)" },
  { value: "tokio-marine-america", label: "Tokio Marine America" },
  {
    value: "american-reliable-insurance-company",
    label: "American Reliable Insurance Company",
  },
  { value: "guideone-insurance", label: "GuideOne Insurance" },
  { value: "national-general-insurance", label: "National General Insurance" },
  { value: "allied-insurance", label: "Allied Insurance" },
  { value: "amerisure-insurance", label: "Amerisure Insurance" },
  { value: "frankenmuth-insurance", label: "Frankenmuth Insurance" },
  { value: "fcci-insurance-group", label: "FCCI Insurance Group" },
  {
    value: "the-cincinnati-insurance-company",
    label: "The Cincinnati Insurance Company",
  },
  {
    value: "brotherhood-mutual-insurance-company",
    label: "Brotherhood Mutual Insurance Company",
  },
  {
    value: "hastings-mutual-insurance-company",
    label: "Hastings Mutual Insurance Company",
  },
  { value: "midwest-insurance-group", label: "Midwest Insurance Group" },
  { value: "penn-america-group", label: "Penn-America Group" },
  {
    value: "utica-national-insurance-group",
    label: "Utica National Insurance Group",
  },
  { value: "tower-hill-insurance-group", label: "Tower Hill Insurance Group" },
  {
    value: "builders-mutual-insurance-company",
    label: "Builders Mutual Insurance Company",
  },
  { value: "builders-insurance-group", label: "Builders Insurance Group" },
  {
    value: "united-states-liability-insurance-group-usli",
    label: "United States Liability Insurance Group (USLI)",
  },
  { value: "medpro-group", label: "MedPro Group" },
  { value: "century-insurance-group", label: "Century Insurance Group" },
  { value: "national-indemnity-company", label: "National Indemnity Company" },
  { value: "onebeacon-insurance-group", label: "OneBeacon Insurance Group" },
  {
    value: "allied-world-assurance-company",
    label: "Allied World Assurance Company",
  },
  {
    value: "hallmark-financial-services",
    label: "Hallmark Financial Services",
  },
  {
    value: "universal-insurance-holdings",
    label: "Universal Insurance Holdings",
  },
  {
    value: "louisiana-workers-compensation-corporation-lwcc",
    label: "Louisiana Workers' Compensation Corporation (LWCC)",
  },
  { value: "icw-group", label: "ICW Group" },
  {
    value: "federated-mutual-insurance-company",
    label: "Federated Mutual Insurance Company",
  },
  { value: "national-casualty-company", label: "National Casualty Company" },
  { value: "canal-insurance-company", label: "Canal Insurance Company" },
  {
    value: "the-main-street-america-group",
    label: "The Main Street America Group",
  },
  {
    value: "frankenmuth-mutual-insurance-company",
    label: "Frankenmuth Mutual Insurance Company",
  },
  {
    value: "intact-insurance-specialty-solutions",
    label: "Intact Insurance Specialty Solutions",
  },
  {
    value: "philadelphia-consolidated-holding-corp",
    label: "Philadelphia Consolidated Holding Corp",
  },
  { value: "zurich-north-america", label: "Zurich North America" },
  { value: "axis-insurance", label: "AXIS Insurance" },
  { value: "rsg-underwriting-managers", label: "RSG Underwriting Managers" },
  {
    value: "new-york-marine-general-insurance-company",
    label: "New York Marine & General Insurance Company",
  },
  {
    value: "west-bend-mutual-insurance-company",
    label: "West Bend Mutual Insurance Company",
  },
  {
    value: "prosight-specialty-insurance",
    label: "ProSight Specialty Insurance",
  },
  { value: "protective-insurance", label: "Protective Insurance" },
  {
    value: "american-international-group-aig",
    label: "American International Group (AIG)",
  },
  { value: "wr-berkley-corporation", label: "W.R. Berkley Corporation" },
  {
    value: "james-river-insurance-company",
    label: "James River Insurance Company",
  },
  {
    value: "national-liability-fire-insurance-company",
    label: "National Liability & Fire Insurance Company",
  },
  {
    value: "cincinnati-financial-corporation",
    label: "Cincinnati Financial Corporation",
  },
  { value: "acadia-insurance", label: "Acadia Insurance" },
  { value: "everest-re-group", label: "Everest Re Group" },
  {
    value: "great-west-casualty-company",
    label: "Great West Casualty Company",
  },
  { value: "merchants-insurance-group", label: "Merchants Insurance Group" },
  {
    value: "ameriprise-auto-home-insurance",
    label: "Ameriprise Auto & Home Insurance",
  },
  { value: "pure-programs", label: "PURE Programs" },
  {
    value: "hdi-global-insurance-company",
    label: "HDI Global Insurance Company",
  },
  { value: "allianz-group", label: "Allianz Group" },
  { value: "encompass-insurance", label: "Encompass Insurance" },
  { value: "employers-insurance-group", label: "Employers Insurance Group" },
  { value: "national-insurance-company", label: "National Insurance Company" },
  {
    value: "universal-north-america-insurance-company",
    label: "Universal North America Insurance Company",
  },
  {
    value: "state-auto-insurance-companies",
    label: "State Auto Insurance Companies",
  },
  { value: "metlife-auto-home", label: "MetLife Auto & Home" },
  { value: "tokio-marine-group", label: "Tokio Marine Group" },
  {
    value: "international-insurance-company-of-hannover",
    label: "International Insurance Company of Hannover",
  },
  {
    value: "swiss-re-corporate-solutions",
    label: "Swiss Re Corporate Solutions",
  },
  {
    value: "united-insurance-company-of-america",
    label: "United Insurance Company of America",
  },
  { value: "global-indemnity-group", label: "Global Indemnity Group" },
  {
    value: "great-american-insurance-company",
    label: "Great American Insurance Company",
  },
  {
    value: "compsource-mutual-insurance-company",
    label: "CompSource Mutual Insurance Company",
  },
  {
    value: "amerisure-mutual-insurance-company",
    label: "Amerisure Mutual Insurance Company",
  },
  { value: "renaissancere-holdings", label: "RenaissanceRe Holdings" },
  { value: "starstone-insurance", label: "StarStone Insurance" },
  {
    value: "ohio-mutual-insurance-group",
    label: "Ohio Mutual Insurance Group",
  },
  { value: "builders-insurance", label: "Builders Insurance" },
  {
    value: "mesa-underwriters-specialty-insurance-company-music",
    label: "Mesa Underwriters Specialty Insurance Company (MUSIC)",
  },
  { value: "southeastern-underwriters", label: "Southeastern Underwriters" },
  {
    value: "preferred-mutual-insurance-company",
    label: "Preferred Mutual Insurance Company",
  },
  { value: "rockingham-insurance", label: "Rockingham Insurance" },
  {
    value: "mountain-west-farm-bureau-mutual-insurance-company",
    label: "Mountain West Farm Bureau Mutual Insurance Company",
  },
  {
    value: "pacific-specialty-insurance-company",
    label: "Pacific Specialty Insurance Company",
  },
  {
    value: "general-star-national-insurance-company",
    label: "General Star National Insurance Company",
  },
  {
    value: "palomar-specialty-insurance",
    label: "Palomar Specialty Insurance",
  },
  { value: "safety-insurance-group", label: "Safety Insurance Group" },
  { value: "kinsale-insurance-company", label: "Kinsale Insurance Company" },
  { value: "employers-holdings-inc", label: "Employers Holdings, Inc." },
  { value: "james-river-group-holdings", label: "James River Group Holdings" },
  { value: "magna-carta-companies", label: "Magna Carta Companies" },
  {
    value: "firstcomp-insurance-company",
    label: "FirstComp Insurance Company",
  },
  { value: "mercury-insurance-group", label: "Mercury Insurance Group" },
  { value: "enstar-group-limited", label: "Enstar Group Limited" },
  { value: "american-safety-insurance", label: "American Safety Insurance" },
  {
    value: "mid-continent-casualty-company",
    label: "Mid-Continent Casualty Company",
  },
  { value: "prime-insurance-company", label: "Prime Insurance Company" },
  { value: "ameritrust-group-inc", label: "AmeriTrust Group, Inc." },
  {
    value: "blue-cross-blue-shield-association-bcbsa",
    label: "Blue Cross Blue Shield Association (BCBSA)",
  },
  { value: "metromile-insurance", label: "Metromile Insurance" },
  { value: "pinnacol-assurance", label: "Pinnacol Assurance" },
  { value: "general-re-corporation", label: "General Re Corporation" },
  {
    value: "employers-mutual-casualty-company-emc",
    label: "Employers Mutual Casualty Company (EMC)",
  },
  {
    value: "capitol-insurance-companies",
    label: "Capitol Insurance Companies",
  },
  { value: "insureon", label: "Insureon" },
  { value: "united-heartland", label: "United Heartland" },
  { value: "compwest-insurance", label: "CompWest Insurance" },
  { value: "midwest-employers-casualty", label: "Midwest Employers Casualty" },
  {
    value: "berkshire-hathaway-specialty-insurance",
    label: "Berkshire Hathaway Specialty Insurance",
  },
  {
    value: "north-american-risk-services-nars",
    label: "North American Risk Services (NARS)",
  },
  { value: "star-insurance-company", label: "Star Insurance Company" },
  {
    value: "westport-insurance-corporation",
    label: "Westport Insurance Corporation",
  },
  { value: "illinois-mutual", label: "Illinois Mutual" },
  {
    value: "preferred-employers-insurance",
    label: "Preferred Employers Insurance",
  },
  {
    value: "transguard-insurance-company-of-america-inc",
    label: "TransGuard Insurance Company of America, Inc.",
  },
  {
    value: "golden-bear-insurance-company",
    label: "Golden Bear Insurance Company",
  },
  { value: "cypress-insurance-group", label: "Cypress Insurance Group" },
  { value: "the-republic-group", label: "The Republic Group" },
  { value: "axa-xl", label: "AXA XL" },
  {
    value: "berkshire-hathaway-homestate-companies",
    label: "Berkshire Hathaway Homestate Companies",
  },
  { value: "concord-group-insurance", label: "Concord Group Insurance" },
  {
    value: "atlantic-specialty-insurance-company",
    label: "Atlantic Specialty Insurance Company",
  },
  {
    value: "employers-assurance-company",
    label: "Employers Assurance Company",
  },
  {
    value: "first-insurance-company-of-hawaii",
    label: "First Insurance Company of Hawaii",
  },
  {
    value: "shelter-insurance-companies",
    label: "Shelter Insurance Companies",
  },
  { value: "safety-insurance", label: "Safety Insurance" },
  {
    value: "protective-life-insurance-company",
    label: "Protective Life Insurance Company",
  },
  {
    value: "first-chicago-insurance-company",
    label: "First Chicago Insurance Company",
  },
  { value: "diamond-insurance-group", label: "Diamond Insurance Group" },
  { value: "lancer-insurance-company", label: "Lancer Insurance Company" },
  { value: "leavitt-group", label: "Leavitt Group" },
  { value: "knight-insurance-group", label: "Knight Insurance Group" },
  { value: "california-insurance-group", label: "California Insurance Group" },
  { value: "tokio-marine-kiln", label: "Tokio Marine Kiln" },
  { value: "acceptance-insurance", label: "Acceptance Insurance" },
  {
    value: "anchor-general-insurance-company",
    label: "Anchor General Insurance Company",
  },
  {
    value: "commercial-insurance-associates",
    label: "Commercial Insurance Associates",
  },
  {
    value: "american-modern-insurance-group",
    label: "American Modern Insurance Group",
  },
  { value: "iat-insurance-group", label: "IAT Insurance Group" },
  {
    value: "ocean-harbor-casualty-insurance-company",
    label: "Ocean Harbor Casualty Insurance Company",
  },
  {
    value: "centauri-specialty-insurance",
    label: "Centauri Specialty Insurance",
  },
  {
    value: "sagesure-insurance-managers",
    label: "SageSure Insurance Managers",
  },
  {
    value: "texas-mutual-insurance-company",
    label: "Texas Mutual Insurance Company",
  },
  { value: "prosight-global", label: "ProSight Global" },
  { value: "conifer-insurance-company", label: "Conifer Insurance Company" },
  {
    value: "american-transit-insurance-company",
    label: "American Transit Insurance Company",
  },
  {
    value: "california-state-compensation-insurance-fund-state-fund",
    label: "California State Compensation Insurance Fund (State Fund)",
  },
  {
    value: "wright-national-flood-insurance-company",
    label: "Wright National Flood Insurance Company",
  },
  { value: "american-financial-group", label: "American Financial Group" },
  { value: "zenith-insurance-company", label: "Zenith Insurance Company" },
];
